/**
 * PKCE (Proof Key for Code Exchange) helpers for OAuth 2.0
 *
 * Implements the PKCE extension as specified in RFC 7636.
 * Used for secure OAuth authentication without client_secret (public client).
 */

import crypto from 'node:crypto';
import { debug } from '../logger.js';

/**
 * Generate a random code verifier for PKCE
 *
 * The code verifier must be:
 * - High-entropy cryptographically random
 * - Between 43 and 128 characters
 * - Containing only alphanumeric characters and '-', '.', '_', '~'
 *
 * @returns {string} Base64URL-encoded code verifier
 */
export function generateCodeVerifier() {
  // Generate 32 bytes of cryptographically secure random data
  // Base64URL encoding results in ~43 characters
  const verifier = crypto.randomBytes(32).toString('base64url');

  debug('Generated code verifier', { length: verifier.length });

  return verifier;
}

/**
 * Generate a code challenge from the verifier
 *
 * Uses SHA-256 hash as specified in PKCE with S256 method.
 *
 * @param {string} verifier - The code verifier generated by generateCodeVerifier()
 * @returns {string} Base64URL-encoded code challenge
 */
export function generateCodeChallenge(verifier) {
  const challenge = crypto
    .createHash('sha256')
    .update(verifier)
    .digest('base64url');

  debug('Generated code challenge', { challengeLength: challenge.length });

  return challenge;
}

/**
 * Generate a cryptographically random state parameter
 *
 * The state parameter is used for CSRF protection during OAuth flow.
 * Must be unique per authentication session.
 *
 * @returns {string} Hex-encoded random state
 */
export function generateState() {
  // Generate 16 bytes of random data (32 hex characters)
  const state = crypto.randomBytes(16).toString('hex');

  debug('Generated state parameter', { state });

  return state;
}

/**
 * Validate state parameter matches expected value
 *
 * @param {string} receivedState - State received from OAuth callback
 * @param {string} expectedState - State generated at start of flow
 * @returns {boolean} True if states match, false otherwise
 */
export function validateState(receivedState, expectedState) {
  const isValid = receivedState === expectedState;

  if (!isValid) {
    debug('State validation failed', {
      received: receivedState,
      expected: expectedState,
    });
  } else {
    debug('State validation successful');
  }

  return isValid;
}

/**
 * Generate all PKCE parameters for OAuth flow
 *
 * Convenience function that generates all required PKCE parameters.
 *
 * @returns {object} Object containing verifier, challenge, and state
 * @returns {string} returns.verifier - Code verifier
 * @returns {string} returns.challenge - Code challenge
 * @returns {string} returns.state - State parameter
 */
export function generatePkceParams() {
  const verifier = generateCodeVerifier();
  const challenge = generateCodeChallenge(verifier);
  const state = generateState();

  debug('Generated PKCE parameters', {
    verifierLength: verifier.length,
    challengeLength: challenge.length,
    stateLength: state.length,
  });

  return { verifier, challenge, state };
}